set -g mouse on
set -g focus-events on

set -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Undercurl
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0


#vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_right "C-l"
# set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# tokoynight night
## Theme
set -g @tokyo-night-tmux_theme "night"
set -g @tokyo-night-tmux_transparent 1

## Number Style
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

## Window Style
### Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 
### No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0

## date
set -g @tokyo-night-tmux_show_datetime 0
## path
set -g @tokyo-night-tmux_show_path 0
# git
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_wbg 1

# plugin list
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin "tmux-plugins/tmux-sensible"

bind-key "K" display-popup -h 90% -w 50% "sesh picker -s -c -H -i -d -t -z"

# Initialize TMUX plugin manager
run "/opt/homebrew/opt/tpm/share/tpm/tpm"
